language: ruby
matrix:
  include:
    - rvm: 2.1.10
      gemfile: spec/support/gemfiles/Gemfile.activesupport-4.0.0
    - rvm: 2.2.7
    - rvm: 2.3.4
    - rvm: 2.4.1
sudo: false
script:
  - bundle exec rake spec features
