language: ruby
matrix:
  include:
    - rvm: 2.1
      gemfile: spec/support/gemfiles/Gemfile.activesupport-4.0.0
    - rvm: 2.2
    - rvm: 2.3
    - rvm: 2.4
    - rvm: 2.5
sudo: false
script:
  - bundle exec rake spec features
